name: Deploy Static Website

on:
  workflow_dispatch:

env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2

jobs:

  # The plan Job - set up the terraform plan and store the plan to the tfapply file as artifact
  plan:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8  

      - name: Install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
            version: 2                         
            verbose: false                     
            arch: amd64
      
      - name: terraform init & plan
        run: |
            terraform init -input=false
            terraform plan -out tfapply
    
      - name: Upload artifact for terraform apply
        uses: actions/upload-artifact@v4
        with:
          name: build-output-tfapply
          path: tfapply
          
# The apply-plan Job - Download the plan generated in the previous phase. apply this plan, then save the terraform.tfstate generated as artifact
  apply-plan:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8  

      - name: Install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
            version: 2                         
            verbose: false                     
            arch: amd64
            
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output-tfapply

      - name: Use the tfapply artifact
        run: |
          terraform init -input=false
          terraform apply -auto-approve tfapply 
      
      - name: Upload Terraform state
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform.tfstate
  
# The wait-for-approval Job - manual approval implement with the environment approval feature
  wait-for-approval:
    runs-on: ubuntu-latest
    needs: apply-plan
    environment:
      name: destroy-approval # Environment requiring manual approval
    steps:
    - name: Wait for Approval
      run: echo "Waiting for manual approval to destroy resources..."

# The destroy Job - Download the Artifact. Here is the terraform.tfstate file generated in the apply step 
  destroy:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8  

      - name: Install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
            version: 2                         
            verbose: false                     
            arch: amd64

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-state

      - name: Use the terraform-state artifact
        run: |
          terraform init -input=false
          terraform refresh
          terraform destroy -auto-approve
